version: '3.7'

services:
  hello:
    build:
      context: ./
      dockerfile: ./Docker/go/Dockerfile
    volumes:
      - ./src:/go/app
    command: realize start --run
    ports:
      - 8888:8888
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
